#!/bin/sh
# athena starting script by rowla
# modified by shazeya@syafi.com (NL101541)

PATH=./:$PATH

L_SRV=RO_login
C_SRV=RO_char
M_SRV=RO_map
SL_SRV=login-server_sql
SC_SRV=char-server_sql
SM_SRV=map-server_sql

print_start() {
#    more << EOF
echo "Athena Starting..."
echo "            (c) 2003 Athena Project"
echo "              modified by shazeya@syafi.com"
echo ""
#echo "Debug informations will appear,"
#echo "since this is a test release."
#echo ""
echo "checking..."
#EOF
}

check_files() {

    for i in ${L_SRV} ${C_SRV} ${M_SRV}
    do
        if [ ! -f ./$i ]; then
            echo "$i does not exist, or can't run."
            echo "Stop. Check your compile."
            exit 1;
        fi
    done

#    more << EOF
echo "Check complete."
echo "Looks good, a nice Athena!"
#EOF
}
    

case $1 in
    'start')
        print_start
        check_files
        chmod +x *${L_SRV}&
        chmod +x *${C_SRV}&
        chmod +x *${M_SRV}&
        exec ./${L_SRV}&
        exec ./${C_SRV}&
        exec ./${M_SRV}&

        echo "Now Started Athena."
;;
    'stop')
        ps ax | grep -E "${SL_SRV}|${SC_SRV}|${SM_SRV}" | awk '{print $1}' | xargs kill
;;
    'restart')
        $0 stop
        $0 start
;;
    *)
        echo "Usage: athena-start { start | stop | restart }"
;;
esac
