#!/bin/sh
# AsuraHosting Script; Author: Edward L.

# Set Date
DATE=`date +%b%d`

# Run map-server_sql
cd /root/Desktop/trunk
if [ ! -f /root/trunk/map-server_sql ];
then
	./map-server 2>&1 | tee -a /root/logs/map-server-$DATE.log
else
	./map-server_sql 2>&1 | tee -a /root/Logs/map-server-$DATE.log
fi
